<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Book;
use App\Models\Category;
use Illuminate\Support\Str;

class BookSeeder extends Seeder
{
    public function run(): void
    {
        // 1. Pastikan Kategori Terkait Sudah Ada di Database
        $kategoriList = [
            'Teknologi',
            'Akuntansi',
            'Bisnis & Manajemen',
            'Umum & Muatan Nasional',
            'Bahasa & Seni',
            'Kuliner',
            'Fashion Design',
            'Hospitality'
        ];

        foreach ($kategoriList as $kat) {
            Category::updateOrCreate(
                ['name' => $kat],
                ['slug' => Str::slug($kat), 'icon' => 'fa-book']
            );
        }

        // 2. Data 37 Buku SMK/MAK Penerbit Erlangga
        $daftarBuku = [
            [
                'isbn' => '0050040210',
                'title' => 'Koding dan Kecerdasan Artifisial SMK/MAK Kelas 10 / KM',
                'author' => 'Sri Wahyudi, Hardo Sujatmiko',
                'publisher' => 'Penerbit Erlangga',
                'year' => 2024,
                'category' => 'Teknologi',
                'description' => 'Buku teks Kurikulum Merdeka yang membahas konsep dasar logika pemrograman, algoritma koding, serta pengenalan dasar-dasar Artificial Intelligence (AI) untuk siswa SMK/MAK Kelas 10.',
            ],
            [
                'isbn' => '0050040220',
                'title' => 'Koding dan Kecerdasan Artifisial SMK/MAK Kelas 11 / KM',
                'author' => 'Sri Wahyudi, Hardo Sujatmiko',
                'publisher' => 'Penerbit Erlangga',
                'year' => 2024,
                'category' => 'Teknologi',
                'description' => 'Tingkat lanjut penerapan algoritma machine learning, pengolahan data kecerdasan buatan, dan studi kasus proyek koding untuk siswa SMK/MAK Kelas 11.',
            ],
            [
                'isbn' => '0053700100',
                'title' => 'UP5 (Unjuk P5) Kebekerjaan SMK/MAK Kelas 10 / KM',
                'author' => 'Arif Ediyanto, Nining Mariyaningsih',
                'publisher' => 'Penerbit Erlangga',
                'year' => 2023,
                'category' => 'Umum & Muatan Nasional',
                'description' => 'Panduan pelaksanaan Projek Penguatan Profil Pelajar Pancasila (P5) tema Kebekerjaan untuk membangun etos kerja siswa SMK Kelas 10.',
            ],
            [
                'isbn' => '0053700110',
                'title' => 'UP5 (Unjuk P5) Kebekerjaan SMK/MAK Kelas 11 / KM',
                'author' => 'Arif Ediyanto, Nining Mariyaningsih',
                'publisher' => 'Penerbit Erlangga',
                'year' => 2023,
                'category' => 'Umum & Muatan Nasional',
                'description' => 'Modul panduan P5 Kebekerjaan lanjutan untuk eksplorasi peluang karir, wirausaha mandiri, dan budaya kerja industri siswa Kelas 11.',
            ],
            [
                'isbn' => '0053700120',
                'title' => 'UP5 (Unjuk P5) Kebekerjaan SMK/MAK Kelas 12 / KM',
                'author' => 'Arif Ediyanto, Nining Mariyaningsih',
                'publisher' => 'Penerbit Erlangga',
                'year' => 2024,
                'category' => 'Umum & Muatan Nasional',
                'description' => 'Persiapan portofolio kerja, uji kesiapan kerja, dan adaptasi lingkungan kerja profesional untuk siswa tingkat akhir Kelas 12.',
            ],
            [
                'isbn' => '0050050180',
                'title' => 'Siap Sertifikasi Profesi Teknisi Muda Jaringan Komputer',
                'author' => 'Amiroh, dkk.',
                'publisher' => 'Penerbit Erlangga',
                'year' => 2023,
                'category' => 'Teknologi',
                'description' => 'Materi panduan uji kompetensi BNSP skema Teknisi Muda Jaringan Komputer mencakup instalasi jaringan LAN, subnetting, dan konfigurasi router.',
            ],
            [
                'isbn' => '0053700130',
                'title' => 'Siap Sertifikasi Kompetensi Teknisi Akuntansi Junior',
                'author' => 'Deky Noviar',
                'publisher' => 'Penerbit Erlangga',
                'year' => 2023,
                'category' => 'Akuntansi',
                'description' => 'Panduan latihan soal dan praktik uji sertifikasi kompetensi teknisi akuntansi junior berbasis SKKNI untuk siswa SMK jurusan Akuntansi.',
            ],
            [
                'isbn' => '0052970131',
                'title' => 'Pendidikan Agama Islam & Budi Pekerti SMK Kelas 10 / KM Revisi',
                'author' => 'Sholeh Dimyathi, dkk.',
                'publisher' => 'Penerbit Erlangga',
                'year' => 2024,
                'category' => 'Umum & Muatan Nasional',
                'description' => 'Buku teks PAI Kurikulum Merdeka Edisi Revisi untuk penguatan aqidah, akhlak mulia, dan fiqih muamalah siswa Kelas 10.',
            ],
            [
                'isbn' => '0052970141',
                'title' => 'Pendidikan Agama Islam & Budi Pekerti SMK Kelas 11 / KM Revisi',
                'author' => 'Sholeh Dimyathi, dkk.',
                'publisher' => 'Penerbit Erlangga',
                'year' => 2024,
                'category' => 'Umum & Muatan Nasional',
                'description' => 'Materi pembelajaran PAI dan Budi Pekerti SMK Kelas 11 dengan pendekatan kontekstual dan integrasi nilai-nilai toleransi.',
            ],
            [
                'isbn' => '0052970151',
                'title' => 'Pendidikan Agama Islam & Budi Pekerti SMK Kelas 12 / KM Revisi',
                'author' => 'Sholeh Dimyathi, dkk.',
                'publisher' => 'Penerbit Erlangga',
                'year' => 2024,
                'category' => 'Umum & Muatan Nasional',
                'description' => 'Materi PAI Kelas 12 persiapan menghadapi dunia kerja dan kehidupan bermasyarakat yang berlandaskan moral dan etika agama.',
            ],
            [
                'isbn' => '0053230190',
                'title' => 'Pendidikan Pancasila SMK/MAK Kelas 10 / KM Revisi',
                'author' => 'Fuad Aljihad',
                'publisher' => 'Penerbit Erlangga',
                'year' => 2024,
                'category' => 'Umum & Muatan Nasional',
                'description' => 'Buku teks Pendidikan Pancasila Kurikulum Merdeka yang membahas kedudukan Pancasila, UUD NRI 1945, Bhinneka Tunggal Ika, dan NKRI.',
            ],
            [
                'isbn' => '0053230200',
                'title' => 'Pendidikan Pancasila SMK/MAK Kelas 11 / KM Revisi',
                'author' => 'Fuad Aljihad',
                'publisher' => 'Penerbit Erlangga',
                'year' => 2024,
                'category' => 'Umum & Muatan Nasional',
                'description' => 'Penerapan nilai-nilai Pancasila dalam demokrasi, hak asasi manusia, dan hukum di Indonesia untuk siswa SMK Kelas 11.',
            ],
            [
                'isbn' => '0053230210',
                'title' => 'Pendidikan Pancasila SMK/MAK Kelas 12 / KM Revisi',
                'author' => 'Fuad Aljihad',
                'publisher' => 'Penerbit Erlangga',
                'year' => 2024,
                'category' => 'Umum & Muatan Nasional',
                'description' => 'Penguatan wawasan kebangsaan, integritas warga negara, dan bela negara dalam era globalisasi bagi siswa Kelas 12.',
            ],
            [
                'isbn' => '0054200400',
                'title' => 'Splash SMK/MAK Grade X / KM (Bahasa Inggris)',
                'author' => 'Anik Muslikah Indriastuti',
                'publisher' => 'Penerbit Erlangga',
                'year' => 2023,
                'category' => 'Bahasa & Seni',
                'description' => 'Buku pengayaan dan asesmen Bahasa Inggris terintegrasi untuk melatih keterampilan listening, speaking, reading, dan writing siswa Kelas 10.',
            ],
            [
                'isbn' => '0054200410',
                'title' => 'Splash Rumpun Teknologi SMK/MAK Grade 11 / KM',
                'author' => 'Anik Muslikah Indriastuti',
                'publisher' => 'Penerbit Erlangga',
                'year' => 2023,
                'category' => 'Bahasa & Seni',
                'description' => 'Modul Bahasa Inggris khusus bidang teknik dan teknologi dengan kosakata teknis, manual reading, dan percakapan industri.',
            ],
            [
                'isbn' => '0054200440',
                'title' => 'Splash Rumpun Bisnis & Manajemen SMK/MAK Grade 11 / KM',
                'author' => 'Anik Muslikah Indriastuti',
                'publisher' => 'Penerbit Erlangga',
                'year' => 2023,
                'category' => 'Bahasa & Seni',
                'description' => 'English for Business and Management: korespondensi bisnis, negosiasi, presentasi produk, dan percakapan formal kantor.',
            ],
            [
                'isbn' => '0054200470',
                'title' => 'Splash Rumpun Bisnis & Manajemen SMK/MAK Grade 12 / KM',
                'author' => 'Anik Muslikah Indriastuti',
                'publisher' => 'Penerbit Erlangga',
                'year' => 2024,
                'category' => 'Bahasa & Seni',
                'description' => 'Tingkat mahir Bahasa Inggris bisnis mencakup wawancara kerja profesional, business proposal, dan laporan keuangan berbahasa Inggris.',
            ],
            [
                'isbn' => '0055100310',
                'title' => 'Matematika SMK/MAK Kelas 10 / KM',
                'author' => 'Arif Ediyanto, Maya Harsasi',
                'publisher' => 'Penerbit Erlangga',
                'year' => 2023,
                'category' => 'Umum & Muatan Nasional',
                'description' => 'Buku Matematika Kurikulum Merdeka yang mencakup materi eksponen, logaritma, barisan & deret, trigonometri, dan statistika.',
            ],
            [
                'isbn' => '0055100530',
                'title' => 'Matematika Rumpun Teknologi SMK/MAK Kelas 11 / KM',
                'author' => 'Arif Ediyanto, Maya Harsasi',
                'publisher' => 'Penerbit Erlangga',
                'year' => 2023,
                'category' => 'Teknologi',
                'description' => 'Matematika terapan khusus bidang teknologi: vektor, matriks, lingkaran, dan kalkulus diferensial untuk pemecahan masalah teknik.',
            ],
            [
                'isbn' => '0055100550',
                'title' => 'Matematika Rumpun Bisnis & Manajemen SMK/MAK Kelas 11 / KM',
                'author' => 'Arif Ediyanto, Maya Harsasi',
                'publisher' => 'Penerbit Erlangga',
                'year' => 2023,
                'category' => 'Bisnis & Manajemen',
                'description' => 'Matematika terapan bisnis: bunga tunggal & majemuk, anuitas, penyusutan aset, dan program linear optimasi usaha.',
            ],
            [
                'isbn' => '0055100610',
                'title' => 'Matematika Rumpun Teknologi SMK/MAK Kelas 12 / KM',
                'author' => 'Arif Ediyanto, Maya Harsasi',
                'publisher' => 'Penerbit Erlangga',
                'year' => 2024,
                'category' => 'Teknologi',
                'description' => 'Kalkulus integral, transformasi geometri, dan distribusi peluang untuk aplikasi perancangan sistem rekayasa dan teknologi.',
            ],
            [
                'isbn' => '0055100630',
                'title' => 'Matematika Rumpun Bisnis & Manajemen SMK Kelas 12 / KM',
                'author' => 'Arif Ediyanto, Maya Harsasi',
                'publisher' => 'Penerbit Erlangga',
                'year' => 2024,
                'category' => 'Bisnis & Manajemen',
                'description' => 'Analisis data statistik bisnis, uji hipotesis sederhana, dan peramalan tren keuangan bagi calon manajer bisnis.',
            ],
            [
                'isbn' => '0054900400',
                'title' => 'Bahasa Indonesia SMK/MAK Kelas 10 / KM',
                'author' => 'Pipit Dwi Komariah',
                'publisher' => 'Penerbit Erlangga',
                'year' => 2023,
                'category' => 'Bahasa & Seni',
                'description' => 'Mempelajari teks laporan hasil observasi, eksposisi, anekdot, cerita rakyat (hikayat), negosiasi, dan biografi.',
            ],
            [
                'isbn' => '0054900411',
                'title' => 'Bahasa Indonesia SMK/MAK Kelas 11 / KM Revisi',
                'author' => 'Pipit Dwi Komariah',
                'publisher' => 'Penerbit Erlangga',
                'year' => 2024,
                'category' => 'Bahasa & Seni',
                'description' => 'Menyusun teks prosedur kompleks, eksplanasi fenomena alam/sosial, ceramah, cerpen, serta proposal karya ilmiah kejuruan.',
            ],
            [
                'isbn' => '0054900420',
                'title' => 'Bahasa Indonesia SMK/MAK Kelas 12 / KM',
                'author' => 'Pipit Dwi Komariah',
                'publisher' => 'Penerbit Erlangga',
                'year' => 2024,
                'category' => 'Bahasa & Seni',
                'description' => 'Penulisan surat lamaran pekerjaan resmi, teks cerita sejarah, editorial pers, dan artikel ilmiah populer.',
            ],
            [
                'isbn' => '0059070070',
                'title' => 'Sejarah SMK/MAK Kelas 10 / KM',
                'author' => 'Ratna Hapsari, M. Adil',
                'publisher' => 'Penerbit Erlangga',
                'year' => 2023,
                'category' => 'Umum & Muatan Nasional',
                'description' => 'Konsep berpikir kronologis, sinkronik, dan diakronik dalam menelusuri sejarah peradaban nusantara dan jalur rempah.',
            ],
            [
                'isbn' => '0059070080',
                'title' => 'Sejarah SMK/MAK Kelas 11 / KM',
                'author' => 'Ratna Hapsari, M. Adil',
                'publisher' => 'Penerbit Erlangga',
                'year' => 2024,
                'category' => 'Umum & Muatan Nasional',
                'description' => 'Perjuangan pergerakan nasional bangsa Indonesia, masa pendudukan, hingga proklamasi kemerdekaan Republik Indonesia.',
            ],
            [
                'isbn' => '0057800011',
                'title' => 'Seni Musik SMK/MAK Kelas 10 / KM Revisi',
                'author' => 'Sugiyanto, T. Agustien Prabarini Rahayu',
                'publisher' => 'Penerbit Erlangga',
                'year' => 2024,
                'category' => 'Bahasa & Seni',
                'description' => 'Apresiasi karya musik tradisional dan modern, eksplorasi bunyi, vokal, aransemen, dan manajemen pertunjukan musik sekolah.',
            ],
            [
                'isbn' => '0055100710',
                'title' => 'Bupena Matematika Jilid 1 SMK/MAK Kelas 10 / KM',
                'author' => 'Kasmina, Toali',
                'publisher' => 'Penerbit Erlangga',
                'year' => 2023,
                'category' => 'Umum & Muatan Nasional',
                'description' => 'Buku pendamping pemantapan konsep dan latihan asesmen mandiri matematika Kurikulum Merdeka untuk Kelas 10.',
            ],
            [
                'isbn' => '0055100720',
                'title' => 'Bupena Matematika Jilid 2 SMK/MAK Kelas 11 / KM',
                'author' => 'Kasmina, Toali',
                'publisher' => 'Penerbit Erlangga',
                'year' => 2023,
                'category' => 'Umum & Muatan Nasional',
                'description' => 'Buku pendamping Bupena Seri Latihan Soal dan Pemahaman Konsep Matematika Fase F Kelas 11 SMK/MAK.',
            ],
            [
                'isbn' => '0055100730',
                'title' => 'Bupena Matematika Jilid 3 SMK/MAK Kelas 12 / KM',
                'author' => 'Kasmina, Toali',
                'publisher' => 'Penerbit Erlangga',
                'year' => 2024,
                'category' => 'Umum & Muatan Nasional',
                'description' => 'Kumpulan soal model AKM dan penalaran matematika lanjutan persiapan kelulusan siswa Kelas 12.',
            ],
            [
                'isbn' => '0053800010',
                'title' => 'Digital Operation (Konsentrasi Keahlian Bisnis Digital) SMK Kelas 11 / KM Revisi',
                'author' => 'Devi Puspitasari',
                'publisher' => 'Penerbit Erlangga',
                'year' => 2024,
                'category' => 'Bisnis & Manajemen',
                'description' => 'Pengoperasian e-commerce, marketplace operations, digital payment gateway, supply chain digital, dan customer relationship management (CRM).',
            ],
            [
                'isbn' => '0053800020',
                'title' => 'Marketing (Konsentrasi Keahlian Bisnis Digital / Retail) SMK/MAK Kelas 11 / KM',
                'author' => 'Widaningsih',
                'publisher' => 'Penerbit Erlangga',
                'year' => 2023,
                'category' => 'Bisnis & Manajemen',
                'description' => 'Strategi pemasaran digital, Search Engine Optimization (SEO), Social Media Marketing, content marketing, dan visual merchandising retail.',
            ],
            [
                'isbn' => '0053800030',
                'title' => 'Pengelolaan Humas & Keprotokolan (Manajemen Perkantoran) SMK Kelas 11 / KM',
                'author' => 'Joko Widodo, Dwi Harti, Suliarsi, Sri Sumarsih',
                'publisher' => 'Penerbit Erlangga',
                'year' => 2023,
                'category' => 'Bisnis & Manajemen',
                'description' => 'Teknik komunikasi publik, tata kelola media relations, perencanaan acara dinas, etiket keprotokolan, dan master of ceremony.',
            ],
            [
                'isbn' => '0053800040',
                'title' => 'Pengelolaan Humas & Keprotokolan (Manajemen Perkantoran) SMK Kelas 12 / KM',
                'author' => 'Joko Widodo, Dwi Harti, Suliarsi, Sri Sumarsih',
                'publisher' => 'Penerbit Erlangga',
                'year' => 2024,
                'category' => 'Bisnis & Manajemen',
                'description' => 'Manajemen krisis komunikasi, evaluasi program kehumasan instansi, dan tata tempat/tata upacara kenegaraan tingkat mahir.',
            ],
            [
                'isbn' => '0053800050',
                'title' => 'Akuntansi Perusahaan Dagang (Konsentrasi Keahlian Akuntansi) SMK/MAK Kelas 11 / KM',
                'author' => 'Dwi Harti, Aris Budianto, Esti Wibawani',
                'publisher' => 'Penerbit Erlangga',
                'year' => 2023,
                'category' => 'Akuntansi',
                'description' => 'Pencatatan transaksi khusus dagang (metode fisik & perpetual), persediaan barang dagang, laporan laba rugi, dan jurnal penutup.',
            ],
            [
                'isbn' => '0053800060',
                'title' => 'Akuntansi Perusahaan Jasa (Konsentrasi Keahlian Akuntansi) SMK/MAK Kelas 11 / KM',
                'author' => 'Dwi Harti, Aris Budianto, Esti Wibawani',
                'publisher' => 'Penerbit Erlangga',
                'year' => 2023,
                'category' => 'Akuntansi',
                'description' => 'Siklus lengkap akuntansi jasa mulai dari bukti transaksi, jurnal umum, buku besar utama dan pembantu, neraca saldo, hingga kertas kerja.',
            ],
        ];

        // 3. Masukkan ke Database dengan cover dan stok otomatis
        foreach ($daftarBuku as $buku) {
            Book::updateOrCreate(
                ['isbn' => $buku['isbn']],
                [
                    'title' => $buku['title'],
                    'author' => $buku['author'],
                    'publisher' => $buku['publisher'],
                    'year' => $buku['year'],
                    'pages' => rand(200, 360),
                    'category' => $buku['category'],
                    'stock_total' => 10,
                    'stock_available' => rand(6, 10),
                    'description' => $buku['description'],
                    'cover_image' => null, // Otomatis menggunakan placeholder/cover accessor bawaan
                ]
            );
        }
    }
}
